Bài tập ở lớp

In [65]:
#1.	Viết chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b.
while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     if b != 0:
       break
     else:
       print("Giá trị b phải khác 0.")
  except ValueError:
    print("Giá trị b phải là số.")

tong = a + b
hieu = a - b
tich = a * b
thuong = a / b

print(f"Phép tính tổng {a} + {b} = {tong}")
print(f"Phép tính hiệu {a} - {b} = {hieu}")
print(f"Phép tính tích {a} * {b} = {tich}")
print(f"Phép tính thương {a} / {b} = {thuong}")

Nhập giá trị a: 5
Nhập giá trị b: 3
Phép tính tổng 5 + 3 = 8
Phép tính hiệu 5 - 3 = 2
Phép tính tích 5 * 3 = 15
Phép tính thương 5 / 3 = 1.6666666666666667


In [66]:
#2. Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi “Hello World”.
str_name = "Hello World"
result = str_name[2:5]
print(f"Các ký tự từ chỉ số 2 đến chỉ số 4 là: {result}")

Các ký tự từ chỉ số 2 đến chỉ số 4 là: llo


In [67]:
#3.	Xóa khoảng trắng thừa ở đầu và cuối chuỗi “   Hello World  ”. Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J.
str_name = "  Hello World "

upto_lower = str_name.lower()
upto_upper = str_name.upper()
remove_space = str_name.strip()
str_namerp = str_name.replace("H", "J")

print(f"Chuyển chuỗi sang dạng thường: {upto_lower}")
print(f"Chuyển chuỗi sang dạng HOA: {upto_upper}")
print(f"Xóa khoảng trắng: {remove_space}")
print(f"Thay ký tự H thành ký tự J: {str_namerp}")


Chuyển chuỗi sang dạng thường:   hello world 
Chuyển chuỗi sang dạng HOA:   HELLO WORLD 
Xóa khoảng trắng: Hello World
Thay ký tự H thành ký tự J:   Jello World 


In [68]:
#4.	In ra “Hello World!” nếu a lớn hơn b.
str_name = "Hello World!"

while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

if a > b:
  print(str_name)
else:
  print("Không thỏa mãn điều kiện")

Nhập giá trị a: 3
Nhập giá trị b: 2
Hello World!


In [69]:
#5.	In ra “Yes” nếu a bằng b, ngược lại in “No”.
str_yes = "Yes"
str_no = "No"

while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

if a == b:
  print(str_yes)
else:
  print(str_no)

Nhập giá trị a: 5
Nhập giá trị b: 5
Yes


In [70]:
#6.	In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

if a == b:
  print("1")
elif a > b:
  print("2")
else:
  print("3")

Nhập giá trị a: 5
Nhập giá trị b: 4
2


In [71]:
#7.	In ra “Hello World!” nếu a bằng b và b bằng d.
str_name = "Hello World!"

while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

while(True):
  try:
     d = int(input("Nhập giá trị d: "))
     break
  except ValueError:
    print("Giá trị d phải là số.")

if a == b and b == d:
  print(str_name)
else:
  print("Không thỏa mãn điều kiện")

Nhập giá trị a: 3
Nhập giá trị b: 3
Nhập giá trị d: 3
Hello World!


In [72]:
#8.	In ra “Hello World!” nếu a bằng b hoặc c bằng d.
str_name = "Hello World!"

while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

while(True):
  try:
     c = int(input("Nhập giá trị c: "))
     break
  except ValueError:
    print("Giá trị c phải là số.")

while(True):
  try:
     d = int(input("Nhập giá trị d: "))
     break
  except ValueError:
    print("Giá trị d phải là số.")

if a == b or c == d:
  print(str_name)
else:
  print("Không thỏa mãn điều kiện.")

Nhập giá trị a: 3
Nhập giá trị b: 3
Nhập giá trị c: 5
Nhập giá trị d: 4
Hello World!


In [73]:
#9.	Viết lại câu lệnh if … else sau lên cùng 1 dòng.
while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

print('Yes') if a > b else print('No')

Nhập giá trị a: 4
Nhập giá trị b: 3
Yes


In [74]:
#10.	Nhập vào 2 số a, b. Thực hiện câu lệnh và cho biết kết quả.
while(True):
  try:
    a = int(input("Nhập giá trị a: "))
    break
  except ValueError:
    print("Giá trị a phải là số.")

while(True):
  try:
     b = int(input("Nhập giá trị b: "))
     break
  except ValueError:
    print("Giá trị b phải là số.")

print("A") if a > b else print("=") if a == b else print("B")

Nhập giá trị a: 4
Nhập giá trị b: 5
B


In [75]:
#11.	Tạo mảng số nguyên a với n phần tử và mảng b chỉ chứa các phần tử chẵn của a.
import numpy as np
arr_A = np.array([3, 4, 1, 6, 3, 7, 10, 11, 12, 4, 45])
filter_arr = arr_A % 2 == 0
arr_B = arr_A[filter_arr]
print(arr_B)



[ 4  6 10 12  4]


In [76]:
#12.	Viết chương trình tính tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5.
sum = 0
n = 999

for i in range(n):
  if i % 3 == 0 or i % 5 == 0:
    sum += i
print(f"Tổng các số từ 0 đến {n} mà là bội của 3 hoặc 5 là: {sum}")

Tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5 là: 232169


In [77]:
#13.	Viết hàm trộn 2 mảng một chiều thành 1 mảng một chiều với mỗi phần tử của mảng mới là tổng của 2 phần tương ứng từ 2 mảng cho trước. Trong quá trình trộn 2 mảng nếu mảng nào còn phần tử thì các phần tử còn lại của mảng đó sẽ đưa vào mảng mới.
arr_A = [3, 9, 1, 4]
arr_B = [2, 7, 4, 3, 2, 8]

min_arr = len(arr_B) if len(arr_A) > len(arr_B) else len(arr_A)

arr_C = arr_A if len(arr_A) > len(arr_B) else arr_B

for i in range(min_arr):
  arr_C[i] = arr_A[i] + arr_B[i]

print(arr_C)

[5, 16, 5, 7, 2, 8]


In [78]:
#14. Cho mảng 2 chiều a có m dòng, n cột chứa số nguyên, viết các hàm sau:
import numpy as np

#a. Tạo mảng a chứa các số nguyên ngẫu nhiên.
def NhapMang():
  m = 0
  n = 0
  while(True):
    try:
      m = int(input("Nhập m số dòng của mảng: "))
      break
    except ValueError:
      print("Giá trị m phải là số.")

  while(True):
    try:
      n = int(input("Nhập n số cột của mảng: "))
      break
    except ValueError:
      print("Giá trị n phải là số.")
  return m, n

#b. Xuất các phần tử thuộc dòng k.
def XuatPhanTuDongK(arr, k):
  if k < 0 or k >= arr.shape[0]:
    print(f"Chỉ số dòng {k} không hợp lệ. Cần nhập trong khoảng [0, {arr.shape[0]-1}].")
  else:
    print(f"Các phần tử thuộc dòng {k}: {arr[k]}")

#c. Xuất các phần tử thuộc cột k.
def XuatPhanTuCotK(arr, k):
  if k < 0 or k >= arr.shape[1]:
    print(f"Chỉ số cột {k} không hợp lệ. Cần nhập trong khoảng [0, {arr.shape[1]-1}].")
  else:
    print(f"Các phần tử thuộc cột {k}: {arr[:, k]}")

#d. Tìm dòng có tổng lớn nhất.
def TimDongTongLonNhat(arr):
  tong_dong = np.sum(arr, axis=1)
  vitri_tong_dong_max = np.argmax(tong_dong)
  print(f"Dòng có tổng lớn nhất là dòng {vitri_tong_dong_max} với tổng là: {tong_dong[vitri_tong_dong_max]}")
  print(f"Các phần tử của dòng này là: {arr[vitri_tong_dong_max]}")

#e. Tìm cột có tích nhỏ nhất.
def TimCotTichNhoNhat(arr):
  tich_cot = np.prod(arr, axis=0)
  vitri_tich_cot_min = np.argmin(tich_cot)
  print(f"Cột có tích nhỏ nhất là cột {vitri_tich_cot_min} với tích là: {tich_cot[vitri_tich_cot_min]}")
  print(f"Các phần tử của cột này là: {arr[:, vitri_tich_cot_min]}")

#f. Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.
def XuatPhanTuDongChanCotLe(arr):
  m, n = arr.shape
  print("Các phần tử thuộc dòng chẵn và cột lẻ:")
  flag = False
  for i in range(m):
    if (i + 1) % 2 == 0:
      for j in range(n):
        if (j + 1) % 2 != 0:
          print(f"arr[{i}, {j}] = {arr[i, j]}")
          flag = True
  if not flag:
    print("Không tìm thấy phần tử nào thỏa mãn điều kiện.")

#g. Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.
def TinhTBCChanDongLe(arr):
  m, n = arr.shape
  sum = 0
  count = 0
  for i in range(m):
    if (i + 1) % 2 != 0:
      for j in range(n):
        if arr[i, j] % 2 == 0:
          sum += arr[i, j]
          count += 1
  if count > 0:
    print(f"Trung bình cộng các phần tử chẵn thuộc dòng lẻ: {sum / count}")
  else:
    print("Không có phần tử chẵn nào thuộc dòng lẻ để tính trung bình cộng.")

#h. Tính trung bình cộng các phần tử thuộc biên.
def TinhTBCPhanTuBien(arr):
  m, n = arr.shape
  sum = 0
  count = 0
  for j in range(n):
    sum += arr[0, j]
    count += 1
  if m > 1:
    for j in range(n):
      sum += arr[m-1, j]
      count += 1
  for i in range(1, m-1):
    sum += arr[i, 0]
    count += 1
  if n > 1:
    for i in range(1, m-1):
      sum += arr[i, n-1]
      count += 1

  if count > 0:
    print(f"Trung bình cộng các phần tử thuộc biên: {sum / count}")
  else:
    print("Không có phần tử biên để tính trung bình cộng.")

#i. Tính trung bình tích các phần tử không thuộc biên.
def TinhTBCTichPhanTuKhongBien(arr):
  m, n = arr.shape
  giatri_phantu = 1
  count = 0
  if m > 2 and n > 2:
    for i in range(1, m - 1):
      for j in range(1, n - 1):
        giatri_phantu *= arr[i, j]
        count += 1

  if count > 0:
    print(f"Trung bình tích các phần tử không thuộc biên (Tích lũy): {giatri_phantu}")
  else:
    print("Không có phần tử không thuộc biên để tính trung bình tích.")

def Menu():
  print("+------------------------------ MENU ------------------------------+")
  print("|01. Tạo mảng a chứa các số nguyên ngẫu nhiên.                     |")
  print("|02. Xuất các phần tử thuộc dòng k.                                |")
  print("|03. Xuất các phần tử thuộc cột k.                                 |")
  print("|04. Tìm dòng có tổng lớn nhất.                                    |")
  print("|05. Tìm cột có tích nhỏ nhất.                                     |")
  print("|06. Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.        |")
  print("|07. Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.    |")
  print("|08. Tính trung bình cộng các phần tử thuộc biên.                  |")
  print("|09. Tính trung bình tích các phần tử không thuộc biên.            |")
  print("|00. Thoát.                                                        |")
  print("+------------------------------- END ------------------------------+")

def Process():
  arr_A = None
  m = 0
  n = 0
  Menu()
  while True:
    try:
      luachon = int(input("Nhập lựa chọn của bạn: "))
      if luachon == 0:
        print("Thoát chương trình.")
        break
      elif luachon == 1:
        m, n = NhapMang()
        arr_A = np.random.randint(1, 100, size=(m, n))
        print("Mảng A đã được tạo:")
        print(arr_A)
      elif luachon == 2:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        try:
          k = int(input("Nhập chỉ số dòng k muốn xuất: "))
          XuatPhanTuDongK(arr_A, k)
        except ValueError:
          print("Chỉ số dòng phải là số nguyên.")
      elif luachon == 3:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        try:
          k = int(input("Nhập chỉ số cột k muốn xuất: "))
          XuatPhanTuCotK(arr_A, k)
        except ValueError:
          print("Chỉ số cột phải là số nguyên.")
      elif luachon == 4:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TimDongTongLonNhat(arr_A)
      elif luachon == 5:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TimCotTichNhoNhat(arr_A)
      elif luachon == 6:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        XuatPhanTuDongChanCotLe(arr_A)
      elif luachon == 7:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TinhTBCChanDongLe(arr_A)
      elif luachon == 8:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TinhTBCPhanTuBien(arr_A)
      elif luachon == 8:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TinhTBCTichPhanTuKhongBien(arr_A)
      elif luachon == 8:
        if arr_A is None:
          print("Mảng chưa được tạo. Vui lòng chọn 1 để tạo mảng.")
          continue
        TinhTBCTichPhanTuKhongBien(arr_A)
      else:
        print("Lựa chọn không hợp lệ. Vui lòng chọn lại.")
    except ValueError:
      print("Lựa chọn phải là số nguyên. Vui lòng thử lại.")

Process()

+------------------------------ MENU ------------------------------+
|01. Tạo mảng a chứa các số nguyên ngẫu nhiên.                     |
|02. Xuất các phần tử thuộc dòng k.                                |
|03. Xuất các phần tử thuộc cột k.                                 |
|04. Tìm dòng có tổng lớn nhất.                                    |
|05. Tìm cột có tích nhỏ nhất.                                     |
|06. Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.        |
|07. Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.    |
|08. Tính trung bình cộng các phần tử thuộc biên.                  |
|09. Tính trung bình tích các phần tử không thuộc biên.            |
|00. Thoát.                                                        |
+------------------------------- END ------------------------------+
Nhập lựa chọn của bạn: 1
Nhập m số dòng của mảng: 3
Nhập n số cột của mảng: 4
Mảng A đã được tạo:
[[39 50 77 32]
 [98 32 60 15]
 [ 2 65 66 55]]
Nhập lựa chọn của bạn: 2
Nhậ

In [79]:
#15. Một sinh viên gồm các thông tin sau:
# Mã sinh viên là chuỗi có 10 ký tự
# Tên là chuỗi tối đa 20 ký tự
# Năm sinh là một số nguyên
# Điểm trung bình là một số thực a.
import datetime

# a. Khai báo lớp SinhVien
class SinhVien:
    def __init__(self, masinhvien, tensinhvien, namsinh, diemtrungbinh):
        if len(masinhvien) != 10:
            raise ValueError(f"Mã sinh viên '{masinhvien}' phải có 10 ký tự.")
        if len(tensinhvien) > 20:
            raise ValueError(f"Tên sinh viên '{tensinhvien}' tối đa 20 ký tự.")
        if not isinstance(namsinh, int) or namsinh < 1900 or namsinh > datetime.datetime.now().year:
            raise ValueError("Năm sinh phải là số nguyên và hợp lệ.")
        if not isinstance(diemtrungbinh, (int, float)) or not (0 <= diemtrungbinh <= 10):
            raise ValueError("Điểm trung bình phải là số thực từ 0 đến 10.")

        self.masinhvien = masinhvien
        self.tensinhvien = tensinhvien
        self.namsinh = namsinh
        self.diemtrungbinh = diemtrungbinh

    def __str__(self):
        return f"Mã SV: {self.masinhvien} | Tên: {self.tensinhvien:<15} | Năm sinh: {self.namsinh} | ĐTB: {self.diemtrungbinh}"


# b. Cho một mảng có n sinh viên
def Tao_Mang_SV():
    danh_sach_sinh_vien = []
    try:
        sv1 = SinhVien("01DH000001", "Nguyễn Thị Lan", 2002, 7.5)
        sv2 = SinhVien("02CD000002", "Trần Thị B", 2001, 8.0)
        sv3 = SinhVien("03DH000003", "Lê Văn C", 2006, 4.0)
        sv4 = SinhVien("04CD000004", "Phan Thị D", 2000, 9.2)
        sv5 = SinhVien("05DH000005", "Phan Thị Lan", 2004, 6.5)
        sv6 = SinhVien("06CD000006", "Hoàng Duy E", 2005, 5.0)
        sv7 = SinhVien("07CD000007", "Võ Thị G", 2008, 3.8)

        danh_sach_sinh_vien.extend([sv1, sv2, sv3, sv4, sv5, sv6, sv7])
        return danh_sach_sinh_vien
    except ValueError as e:
        print(f"Lỗi khi tạo sinh viên: {e}")
        return []

# c. Đếm sinh viên đủ điều kiện lên lớp (ĐTB >= 5)
def dem_sinh_vien_du_dieu_kien_len_lop(danh_sach_sinh_vien):
    count = 0
    for sv in danh_sach_sinh_vien:
        if sv.diemtrungbinh >= 5:
            count += 1
    return count

# d. Xuất các sinh viên đủ 20 tuổi
def xuat_sinh_vien_du_20_tuoi(danh_sach_sinh_vien, namhientai):
    sinh_vien_du_tuoi = []
    for sv in danh_sach_sinh_vien:
        tuoi = namhientai - sv.namsinh
        if tuoi >= 20:
            sinh_vien_du_tuoi.append(sv)
    return sinh_vien_du_tuoi

# e. Đếm số sinh viên học hệ đại học (chứa 'DH' ở vị trí 2,3 - tức index [2:4] trong mảng 0-indexed)
def dem_sinh_vien_he_dai_hoc(danh_sach_sinh_vien):
    count = 0
    for sv in danh_sach_sinh_vien:
        if len(sv.masinhvien) >= 4 and sv.masinhvien[2:4] == "DH":
            count += 1
    return count

# f. Cho biết trong mảng có bao nhiêu sinh viên có tên «Lan»
def dem_sinh_vien_ten_lan(danh_sach_sinh_vien):
    count = 0
    for sv in danh_sach_sinh_vien:
        if sv.tensinhvien.split()[-1].lower() == "lan":
            count += 1
    return count

# g. Cho biết trong mảng có bao nhiêu sinh viên có họ «Phan»
def dem_sinh_vien_ho_phan(danh_sach_sinh_vien):
    count = 0
    for sv in danh_sach_sinh_vien:
        if sv.tensinhvien.split()[0].lower() == "phan":
            count += 1
    return count

if __name__ == "__main__":

    print("b. TẠO MẢNG SINH VIÊN")
    ds_sinh_vien = Tao_Mang_SV()
    for sv in ds_sinh_vien:
        print(sv)

    print("\nc. ĐẾM SINH VIÊN ĐỦ ĐIỀU KIỆN LÊN LỚP (ĐTB >= 5)")
    so_sv_len_lop = dem_sinh_vien_du_dieu_kien_len_lop(ds_sinh_vien)
    print(f"Có {so_sv_len_lop} sinh viên đủ điều kiện.")

    print("\nd. CÁC SINH VIÊN ĐỦ 20 TUỔI (Tính đến năm hiện tại)")
    nam_hien_tai = datetime.datetime.now().year
    ds_du_tuoi = xuat_sinh_vien_du_20_tuoi(ds_sinh_vien, nam_hien_tai)
    if ds_du_tuoi:
        for sv in ds_du_tuoi:
            print(sv)
    else:
        print("Không có sinh viên nào đủ 20 tuổi.")

    print("\ne. SỐ SINH VIÊN HỆ ĐẠI HỌC (Mã có 'DH' ở vị trí thứ 3 và 4)")
    so_sv_dh = dem_sinh_vien_he_dai_hoc(ds_sinh_vien)
    print(f"Có {so_sv_dh} sinh viên hệ Đại học.")

    print("\nf. SỐ SINH VIÊN TÊN 'LAN'")
    so_sv_ten_lan = dem_sinh_vien_ten_lan(ds_sinh_vien)
    print(f"Có {so_sv_ten_lan} sinh viên tên Lan.")

    print("\ng. SỐ SINH VIÊN HỌ 'PHAN'")
    so_sv_ho_phan = dem_sinh_vien_ho_phan(ds_sinh_vien)
    print(f"Có {so_sv_ho_phan} sinh viên họ Phan.")

b. TẠO MẢNG SINH VIÊN
Mã SV: 01DH000001 | Tên: Nguyễn Thị Lan  | Năm sinh: 2002 | ĐTB: 7.5
Mã SV: 02CD000002 | Tên: Trần Thị B      | Năm sinh: 2001 | ĐTB: 8.0
Mã SV: 03DH000003 | Tên: Lê Văn C        | Năm sinh: 2006 | ĐTB: 4.0
Mã SV: 04CD000004 | Tên: Phan Thị D      | Năm sinh: 2000 | ĐTB: 9.2
Mã SV: 05DH000005 | Tên: Phan Thị Lan    | Năm sinh: 2004 | ĐTB: 6.5
Mã SV: 06CD000006 | Tên: Hoàng Duy E     | Năm sinh: 2005 | ĐTB: 5.0
Mã SV: 07CD000007 | Tên: Võ Thị G        | Năm sinh: 2008 | ĐTB: 3.8

c. ĐẾM SINH VIÊN ĐỦ ĐIỀU KIỆN LÊN LỚP (ĐTB >= 5)
Có 5 sinh viên đủ điều kiện.

d. CÁC SINH VIÊN ĐỦ 20 TUỔI (Tính đến năm hiện tại)
Mã SV: 01DH000001 | Tên: Nguyễn Thị Lan  | Năm sinh: 2002 | ĐTB: 7.5
Mã SV: 02CD000002 | Tên: Trần Thị B      | Năm sinh: 2001 | ĐTB: 8.0
Mã SV: 03DH000003 | Tên: Lê Văn C        | Năm sinh: 2006 | ĐTB: 4.0
Mã SV: 04CD000004 | Tên: Phan Thị D      | Năm sinh: 2000 | ĐTB: 9.2
Mã SV: 05DH000005 | Tên: Phan Thị Lan    | Năm sinh: 2004 | ĐTB: 6.5
Mã SV: 06CD000006 